// ---------------------------------------------------------------------------
// This file has been generated by the Web Dynpro Code Generator
// DON'T MODIFY!!! CHANGES WILL BE LOST WHENEVER THE FILE GETS GENERATED AGAIN
// ---------------------------------------------------------------------------
package org.example.wdp;

/**
 * This interface encapsulates all messages for this component. 
 * The message constants can be used in conjunction with 
 * the IWDMessageManager.reportMessage method.
 */
public interface IMessageSampleComponent {
}
